INSERT INTO product (id, region, weight, price, name) VALUES (1, 'South Korea', 150, 78.99, 'Beauty of Joseon Relief Sun SPF50+');
INSERT INTO product (id, region, weight, price, name) VALUES (2, 'South Korea', 50, 89.99, 'Beauty of Joseon Glow Serum Propolis + Niacinamide');
INSERT INTO product (id, region, weight, price, name) VALUES (3, 'South Korea', 50, 92.99, 'Beauty of Joseon Calming Serum Green Tea + Panthenol');
INSERT INTO product (id, region, weight, price, name) VALUES (4, 'South Korea', 150, 84.99, 'Beauty of Joseon Dynasty Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (5, 'South Korea', 150, 74.99, 'Beauty of Joseon Ginseng Essence Water');
INSERT INTO product (id, region, weight, price, name) VALUES (6, 'South Korea', 30, 69.99, 'Beauty of Joseon Revive Eye Serum Ginseng + Retinal');
INSERT INTO product (id, region, weight, price, name) VALUES (7, 'South Korea', 150, 81.99, 'Beauty of Joseon Green Plum Refreshing Cleanser');
INSERT INTO product (id, region, weight, price, name) VALUES (8, 'South Korea', 50, 79.99, 'Beauty of Joseon Glow Deep Serum Rice + Alpha-Arbutin');
INSERT INTO product (id, region, weight, price, name) VALUES (9, 'South Korea', 150, 76.99, 'Beauty of Joseon Matte Sun Stick Mugwort + Camellia');
INSERT INTO product (id, region, weight, price, name) VALUES (10, 'South Korea', 150, 88.99, 'Beauty of Joseon Red Bean Water Gel');
INSERT INTO product (id, region, weight, price, name) VALUES (11, 'South Korea', 100, 64.99, 'COSRX Advanced Snail 96 Mucin Power Essence');
INSERT INTO product (id, region, weight, price, name) VALUES (12, 'South Korea', 100, 59.99, 'COSRX Low pH Good Morning Gel Cleanser');
INSERT INTO product (id, region, weight, price, name) VALUES (13, 'South Korea', 100, 79.99, 'COSRX Advanced Snail 92 All In One Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (14, 'South Korea', 30, 72.99, 'COSRX The Niacinamide 15 Serum');
INSERT INTO product (id, region, weight, price, name) VALUES (15, 'South Korea', 100, 74.99, 'COSRX BHA Blackhead Power Liquid');
INSERT INTO product (id, region, weight, price, name) VALUES (16, 'South Korea', 100, 76.99, 'COSRX AHA 7 Whitehead Power Liquid');
INSERT INTO product (id, region, weight, price, name) VALUES (17, 'South Korea', 150, 69.99, 'COSRX Full Fit Propolis Synergy Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (18, 'South Korea', 100, 82.99, 'COSRX Full Fit Propolis Light Ampoule');
INSERT INTO product (id, region, weight, price, name) VALUES (19, 'South Korea', 70, 66.99, 'COSRX Acne Pimple Master Patch');
INSERT INTO product (id, region, weight, price, name) VALUES (20, 'South Korea', 150, 71.99, 'COSRX Hydrium Watery Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (21, 'South Korea', 50, 109.99, 'Dr. Althea 345 Relief Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (22, 'South Korea', 150, 96.99, 'Dr. Althea Azulene 147HA Intensive Soothing Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (23, 'South Korea', 150, 92.99, 'Dr. Althea To Be Youthful Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (24, 'South Korea', 200, 84.99, 'Dr. Althea Amino Acid Gentle Bubble Cleanser');
INSERT INTO product (id, region, weight, price, name) VALUES (25, 'South Korea', 150, 89.99, 'Dr. Althea Premium Cica Skin Calming Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (26, 'South Korea', 50, 104.99, 'Dr. Althea Vitamin C Boosting Serum');
INSERT INTO product (id, region, weight, price, name) VALUES (27, 'South Korea', 150, 99.99, 'Dr. Althea Natural Radiance Essence');
INSERT INTO product (id, region, weight, price, name) VALUES (28, 'South Korea', 150, 91.99, 'Dr. Althea Pure Grinding Cleansing Balm');
INSERT INTO product (id, region, weight, price, name) VALUES (29, 'South Korea', 50, 107.99, 'Dr. Althea Resveratrol Intensive Repair Serum');
INSERT INTO product (id, region, weight, price, name) VALUES (30, 'South Korea', 100, 94.99, 'Dr. Althea Green Relief Ampoule');
INSERT INTO product (id, region, weight, price, name) VALUES (31, 'South Korea', 150, 98.99, 'I’m From Rice Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (32, 'South Korea', 150, 89.99, 'I’m From Mugwort Essence');
INSERT INTO product (id, region, weight, price, name) VALUES (33, 'South Korea', 120, 102.99, 'I’m From Ginseng Serum');
INSERT INTO product (id, region, weight, price, name) VALUES (34, 'South Korea', 110, 76.99, 'I’m From Honey Mask');
INSERT INTO product (id, region, weight, price, name) VALUES (35, 'South Korea', 120, 79.99, 'I’m From Mugwort Mask');
INSERT INTO product (id, region, weight, price, name) VALUES (36, 'South Korea', 150, 83.99, 'I’m From Fig Boosting Essence');
INSERT INTO product (id, region, weight, price, name) VALUES (37, 'South Korea', 120, 81.99, 'I’m From Pear Soothing Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (38, 'South Korea', 30, 97.99, 'I’m From Vitamin Tree Water Gel');
INSERT INTO product (id, region, weight, price, name) VALUES (39, 'South Korea', 150, 87.99, 'I’m From Beet Refresh Pads');
INSERT INTO product (id, region, weight, price, name) VALUES (40, 'South Korea', 30, 104.99, 'I’m From Black Ginseng Serum');
INSERT INTO product (id, region, weight, price, name) VALUES (41, 'South Korea', 150, 72.99, 'Round Lab 1025 Dokdo Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (42, 'South Korea', 150, 79.99, 'Round Lab Birch Juice Moisturizing Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (43, 'South Korea', 150, 76.99, 'Round Lab Birch Juice Moisturizing Cleanser');
INSERT INTO product (id, region, weight, price, name) VALUES (44, 'South Korea', 150, 74.99, 'Round Lab 1025 Dokdo Cleanser');
INSERT INTO product (id, region, weight, price, name) VALUES (45, 'South Korea', 200, 83.99, 'Round Lab Birch Juice Moisturizing Sunscreen');
INSERT INTO product (id, region, weight, price, name) VALUES (46, 'South Korea', 150, 89.99, 'Round Lab Soybean Nourishing Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (47, 'South Korea', 100, 85.99, 'Round Lab Soybean Nourishing Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (48, 'South Korea', 150, 81.99, 'Round Lab Mugwort Calming Toner');
INSERT INTO product (id, region, weight, price, name) VALUES (49, 'South Korea', 100, 88.99, 'Round Lab Pine Tree Soothing Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (50, 'South Korea', 150, 79.99, 'Round Lab Pine Tree Cica Pad');
INSERT INTO product (id, region, weight, price, name) VALUES (51, 'South Korea', 50, 77.99, 'COSRX Hyaluronic Acid Intensive Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (52, 'South Korea', 150, 68.99, 'Beauty of Joseon Green Tea Cleansing Water');
INSERT INTO product (id, region, weight, price, name) VALUES (53, 'South Korea', 150, 93.99, 'I’m From Rice Cream');
INSERT INTO product (id, region, weight, price, name) VALUES (54, 'South Korea', 100, 95.99, 'Dr. Althea Skin Relief Essence');
INSERT INTO product (id, region, weight, price, name) VALUES (55, 'South Korea', 150, 74.99, 'Round Lab Birch Juice Toner');